
<div class="grid-x" id="div_grid">

<!-- foundation magellan sticky helper -->
<div class="cell small-3 large-2" data-sticky-container id="stick_panel">
<div data-sticky data-anchor="div_grid">
<ul class="vertical menu" data-magellan>   
        <?= $magellan_dd ?>
</ul>
</div>
</div>


<!-- accordion panel -->
<div class="cell small-9 large-10" id="acc_panel">
<ul class="accordion" data-accordion>
   <?= $accordion_li ?>
</ul>
</div>



</div>


<!-- for rendering math formulas -->
<script src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=AM_HTMLorMML"></script>

