<li id="<?= $li_id ?>" class="accordion-item" <?= !empty($li_data) ? $li_data : "" ?> data-accordion-item>

	<a id="<?= $a_id ?>" href="#<?= $div_id ?>"  class="accordion-title">
	<?= $title ?>
	<span class="subheader float-right" style="margin-right:2rem;">
		<?= !empty($type) ? ucfirst($type) : "" ?>
		<?= !empty($type) && !empty($date)? " &nbsp;&bullet;&nbsp; " : "" ?>
		<?= !empty($date) ? $date : "" ?>		
	</span>
	</a>
	
	<div id="<?= $div_id ?>" class="accordion-content" data-tab-content>
		<?= !empty($formula) ? $formula : "" ?>
			
		<?= $text ?>
	</div>	
</li>