
<!-- foundation magellan sticky helper -->
<div data-magellan-expedition="fixed">
    <dl class="sub-nav sub-top">
        <?= $magellan_dd ?>
    </dl>
</div>

<!-- accordion panel -->
<div class="small-12 columns">
    <ul class="accordion" data-accordion>
        <?= $accordion_li ?>
    </ul>
</div>


<!-- for rendering math formulas -->
<script src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=AM_HTMLorMML"></script>

