<!DOCTYPE html>
<!--[if IE 9]><html class="lt-ie10" lang="en" > <![endif]-->
<html class="no-js" lang="en" dir="ltr" data-useragent="Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.2; Trident/6.0)">
    <head>
        <title><?= $title ?></title>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
         <meta name="Description" content="D-Framework : a simple PHP framework"/>
        <meta name="keywords" lang="eng" content="D-framework"/>
        <meta http-equiv="Content-Language" content="eng"/>
        <link rel="stylesheet" type="text/css" href="css/foundation.min.css"/>
        <link rel="stylesheet" type="text/css" href="css/foundation-icons.css"/>
         <link rel="stylesheet" type="text/css" href="css/motion-ui.min.css"/>
        <link rel="stylesheet" type="text/css" href="css/form/dams-style.css"/>
        <script src="js/jsSha2/sha256.js"></script>            			
    </head>

    <body>
        <!-- Menu -->
        <?= $menu ?>
        
        <!-- Modal -->
        <div id="modal"></div>

        <!-- Content -->
        <div id="div_page" class="row top">
        <?= $content ?>
        </div>

        <!-- JS script -->
        <script src="js/vendor/jquery.js"></script>
        <script src="js/vendor/what-input.js"></script>
        <script src="js/vendor/foundation.js"></script>         
        <script src="js/controller/damsController.js"></script>
        <script>
          $(document).foundation();
          $(document).dams();
        </script>
    </body>
</html>
