<div id="modal_content" class="reveal-modal medium" data-reveal aria-hidden="true" role="dialog">

<div class="small-12 columns">
	<?= !empty($title) ? "<h3 class='subheader'>":"" ?>
	<?= !empty($icon) ? "<i class='".$icon."'></i> " : "" ?>
	<?= !empty($title) ? $title."</h3>" : "" ?>	
	
	<?= !empty($include) ? "<div class='panel radius'>".$include."</div>" : "" ?>
 	<?= $texts ?>
	<?= $infos ?>
</div>
<a class="close-reveal-modal" aria-label="close">&bull;</a>
</div>