<div id="modal_content" class="reveal-modal tiny" data-reveal aria-labelledby="login" aria-hidden="true" role="dialog">
<form id="login_form" name="login_form" encType="multipart/form-data" action="" method="POST">
    <div class="large-12 columns">
        <h3 class="subheader"><i class="fi-lock"></i> Login</h3>

        <!-- Login message -->
        <div class="row">
            <div id="login_notification"></div>
        </div>

        <div class="panel radius">

            <!-- User Name -->
            <div class="row">
                <div class="large-12 columns">
                    <div class="row collapse prefix-radius">
                        <div class="small-4 columns">
                            <span class="prefix green"><i class="fi-torso"></i></span>
                        </div>
                        <div class="small-8 columns">
                            <input type="text" size="30" name="username" id="username" required  maxlength="30" placeholder="user name"/>
                        </div> 
                    </div>         
                </div>
            </div>

            <!-- Password Name -->
            <div class="row">
                <div class="large-12 columns">
                    <div class="row collapse prefix-radius">
                        <div class="small-4 columns">
                            <span class="prefix green"><i class="fi-key"></i></span>
                        </div>
                        <div class="small-8 columns">
                            <input type="password" size="30" name="password" id="password" required  maxlength="30" placeholder="password"/>
                        </div>
                    </div>
                </div> 
                <?//special data hidden input (to send crypted data package without ssl)?>
                <input type="hidden" name="data" id="data"/>
            </div>
        </div>

        <!-- submit button -->
        <div class="row">
            <div class="large-12 columns">
                <ul class="button-group round right">
                    <li>
                        <button class="close-reveal-modal small button" name="close" id="close"><i class="fi-x"></i> Cancel</button>
                    </li>
                    <li>
                        <button type="submit" class="small button" name="submit" id="submit"><i class="fi-check"></i> Submit</button>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</form>
<a class="close-reveal-modal" aria-label="close">&bull;</a>
</div>
