
<div class="fixed">
    <nav class="top-bar" data-topbar role="navigation">
        <!-- top-bar title -->
        <ul class="title-area">
            <li class="name">
                <h1><a href="/"><?= $title ?></a></h1>
            </li>
            <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
        </ul>

        <!-- top-bar section -->
        <section class="top-bar-section">
            <ul class="right">
                <?= $menu ?>
            </ul>
        </section>
    </nav>
</div>
