

<div class="title-bar" data-responsive-toggle="responsive-menu"	data-hide-for="medium">
	<button class="menu-icon" type="button" data-toggle="responsive-menu"></button>
	<div class="title-bar-title"><?= $title ?></div>
</div>

<div class="top-bar" data-data-sticky id="responsive-menu">
	<!-- top-bar title -->
	<div class="title-bar-left show-for-medium">
		<span class="title-bar-title"><a href="/"><?= $title ?></a></span>
	</div>

	<!-- top-bar section -->
	<div class="top-bar-right">
		<ul class="vertical medium-horizontal menu"
			data-responsive-menu="accordion medium-dropdown">
                <?= $menu ?>
            </ul>
	</div>
</div>
