<div class="tabs-panel <?= $active ?>" id="<?= $tab_id ?>">

	<div>
		<?= !empty($abstract) ? "<span class='label'>".$abstract."</span>" : "" ?>

		<div class="callout">
		
		<?= !empty($screens) ? 
	   '<div class="orbit" role="region" aria-label="Screenshots" data-orbit>' .
	   '<div class="orbit-wrapper">' . PHP_EOL .
	   
	   '<div class="orbit-controls">' .
	   '<button class="orbit-previous"><span class="show-for-sr">Previous Slide</span>&#9664;&#xFE0E;</button>' .
	   '<button class="orbit-next"><span class="show-for-sr">Next Slide</span>&#9654;&#xFE0E;</button>' .
	   '</div>' .  PHP_EOL .
	   
	   '<ul class="orbit-container">' .
		 $screens  .
		 '</ul>' .  PHP_EOL .
	   
		'<nav class="orbit-bullets">' .
		 $orbitBullets .
		'</nav>' . PHP_EOL . 
		 
	   '</div>' .
	   '</div>'
        : "" ?>
        
			<?= !empty($image) && empty($screens) ? "<span class='left round' style='margin:10px;'><img src='".$image."'></span>" : "" ?>
			
			<?= !empty($comment) ? "<div style='margin:10px;'>".$comment."</div><hr>" : "" ?>
		
			<div style="margin:10px;"><?= $text ?></div>
			
			<?= isset($progress) && $progress != NULL ? 
			"<hr><span class='subheader' style='padding-bottom:10px;'>Current progress</span>" .
			"<div class='progress'>" .
			"<span class='meter green' style='width:". $progress ."%'>" .
			"<p class='percent'>".$progress."%</p>".
			"</span>".
			"</div>" : "" ?>
		</div>
		
		<?= !empty($infos) ? $infos : "" ?>
	</div>

</div>